### ISSUE TITLE
Setup E2E testing 

### ISSUE THREAD

**Issue by jooola** [directus/sdk-python#16]
We should add e2e testing in order to prevent any breakage.

I propose to use a docker environment, for both local and CI testing. I already created such environment here https://github.com/directus/gatsby-source/blob/master/docker-compose.yml

Once e2e testing is created new api calls should always be backed by e2e tests, otherwise it won't be accepted. CI will enforce this.

**Comment by vvatelot** [comment]
@jooola what do you want to embed with docker-compose? Local [directus](https://docs.directus.io/installation/docker.html) with DB?

**Comment by jooola** [comment]
We will import the exact same file I described in the ticket description. It will create a directus api and a database for storing test data.

Future version of Directus API will allow to create Sqlite inmemory database and will really simplify e2e testing, but for now this is the way I found to create proper testing. Testing data should be stored in a shared repo so that every tools using e2e testing will share the same specs.
