### ISSUE TITLE
Use poetry as package manager

### ISSUE THREAD

**Issue by jooola** [directus/sdk-python#17]
I don't know the benefit over make, but I would like to give python-poetry a try for managing this package.

https://python-poetry.org/

We can translate make recipes to poetry scripts, similar to npm package.json.

Publishing to pypi sounds easier.

Needs to be investigated.

**Comment by jooola** [comment]
I just tried poetry, and it will not replace the makefile, it will only take care off dependencies and publishing. So maybe this isn't the best idea.

**Comment by vvatelot** [comment]
Ok, so let's use makefile for generic tasks and maybe we can use a github action to publish on pypi on release event: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by jooola** [comment]
That was the plan, but haven't looked at it yet.
We need to create a new issue regarding publishing, since we need approval of the maintainers of this project.

Thanks for the link

**Comment by jooola** [comment]
Resolved by #20
