### ISSUE TITLE
API implementation defects

### ISSUE THREAD

**Issue by Danny-Whitt-Bose** [directus/sdk-python#38]
This is a very useful package as it saved a bunch of time for my current project.

While using it, though, several implementation defects were encountered. So I wanted to describe them here, along with a patch, for consideration by the maintainers.

It is by no means an exhaustive list but only includes those specific blocking defects I observed.

The patch addresses these items:
- correct handling of missing `email` and `password` parameters in the `DirectusClient` class
- fix handling of the `filter` parameter in `get_files_list` function per API
- add missing `filename_disk` parameter in `create_file` function required for base64 string of file data (note: undocumented in API)
- fix recursion issue in auth token refresh logic upon expiry
- correctly reset authorization header with refreshed auth token

Hope this helps!
[sdk-python-0.1.1.diff.txt](https://github.com/directus/sdk-python/files/4919873/sdk-python-0.1.1.diff.txt)

**Comment by vvatelot** [comment]
Hello @Danny-Whitt-Bose many thanks for your contribution.
Instead of making a patch, do you think it could be possible to open a Pull Request? That would be really great to discuss the changes you propose

**Comment by Danny-Whitt-Bose** [comment]
PRs opened per @vvatelot's suggestion.

**Comment by jooola** [comment]
@Danny-Whitt-Bose Thanks for your help ! We still have one open PR, I just need further explanation on a small change.

Cheers :beers:

**Comment by jooola** [comment]
All bugs have been resolved ! Thanks again !
