### ISSUE TITLE
Add headers with get requests

### ISSUE THREAD

**Issue by Manish-Muttreja-Bose** [directus/sdk-python#45]
Hi,

We are using the SDK with Cloudfront, and it turns out that our `get` requests fail because the API sets `Request/Headers/Content-Length=2`. 
 According to RFC-7230 section 3.3.2, a user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body.  We can resolve our error if we can supply a header, so we will simply send a header with `content-length` to be 0. Anyone using CloudFront will probably hit this error too.

Unfortunately, I can't post our requests but is it possible to send headers with requests using the API?

**Comment by Shadlington** [comment]
If _make_request's data param defaults to None rather than {}, this problem goes away as it will stop trying to encode an empty JSON object on every request without a payload passed in.
